# Generated by Django 4.1.7 on 2023-04-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0009_alter_customer_amount_alter_customer_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bonus',
            field=models.CharField(default='0', max_length=200, null=True),
        ),
    ]
