# Generated by Django 4.1.7 on 2023-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0010_alter_customer_amount_alter_customer_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='0', max_length=200, null=True)),
                ('deposit', models.CharField(default='0', max_length=200, null=True)),
                ('bonus', models.CharField(default='0', max_length=200, null=True)),
                ('plan', models.CharField(default='Plan1', max_length=200, null=True)),
            ],
        ),
    ]
