# Generated by Django 4.1.7 on 2023-04-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bit', '0012_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
